### ISSUE TITLE
Overview & What we need (06.09.16)

### ISSUE THREAD

**Issue by 91juhwang** [cortesg/CollaborativeWebsite#2]
- Created the basic structure of our "Bridge Builder" website. 

Issues: 
**
1. Change the design of each page (home&about) according to the contact page. 
2. Add contents and display them in pretty design. (Should be consistent with our current design of contact page)

*\* 
- Any other questions or comments on here

**Comment by 91juhwang** [comment]
testing comment section

**Comment by cortesg** [comment]
the styling is pretty consistent now! :)
